# Gradle Properties
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Disable stonecutter warning
dev.kikugie.stonecutter.hard_mode=true

# Mod Properties
mod_id=fern_config
mod_name=Fern Config
mod_version=0.0.1
maven_group=dev.lemonnik

mod_description=config
mod_authors=Lemonnik
mod_homepage=https://modrinth.com/mod/fern-config/
mod_sources=https://github.com/Lemonnik6484/FernConfig/
mod_issue=https://github.com/Lemonnik6484/FernConfig/issues/
mod_license=PolyForm Shield License 1.0.0

# Versioned Dependencies
minecraft_version=[VERSIONED]
platform=[VERSIONED]
minecraft_dependency=[VERSIONED]

# fabric
fabric_loader_version=0.18.6
modmenu_version=[VERSIONED]
fabric_api_version=[VERSIONED]

# forge
forge_version=[VERSIONED]

# neoforge
neoforge_version=[VERSIONED]
